require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '**/._*'
    - 'db/schema.rb'
    - 'lib/tools/*'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Enabled: true
  Exclude:
    - config/routes.rb

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  EnforcedStyle: single_quotes

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'method_call']
